---
group:
  alumet:
    exists: true
user:
  alumet:
    exists: true
file:
  /etc/alumet/alumet-config.toml:
    exists: true
    owner: alumet
    group: alumet
    mode: "0644"
  /usr/bin/alumet-agent:
    exists: true
    owner: alumet
    group: alumet
    mode: "0555"

command:
  'run alumet-agent':
    exec: "/usr/bin/alumet-agent --config /etc/alumet/alumet-config.toml --plugins csv,perf,procfs,socket-control exec -- sleep 1 && [ -s alumet-output.csv ]"
    exit-status: 0
