---
package:
  alumet:
    installed: true

service:
  alumet:
    enabled: false
    running: false

file:
  /usr/lib/alumet-agent:
    exists: true
    mode: "555"
  /usr/lib/systemd/system/alumet.service:
    exists: true
    mode: "644"
  /usr/bin/alumet-agent:
    exists: true
    mode: "755"
  /etc/alumet/alumet-config.toml:
    exists: true
    mode: "644"

command:
  'run alumet-agent':
    exec: "alumet-agent --plugins csv,procfs exec -- sleep 1 && cat alumet-output.csv"
    exit-status: 0
