[plugins.k8s]
path = "/sys/fs/cgroup/kubepods.slice/"
poll_interval = "1s"
kubernetes_api_url = "https://127.0.0.1:8080"
hostname = ""
token_retrieval = "kubectl"
enable = false

[plugins.OAR3]
path = "/sys/fs/cgroup/"
poll_interval = "1s"
enable = false

[plugins.oar2-plugin]
path = "/sys/fs/cgroup"
poll_interval = "1s"
enable = false

[plugins.csv]
output_path = "alumet-output.csv"
force_flush = true
append_unit_to_metric_name = true
use_unit_display_name = true
csv_delimiter = ";"
enable = true

[plugins.influxdb]
host = "http://localhost:8086"
token = "FILL ME"
org = "FILL ME"
bucket = "FILL ME"
attributes_as = "field"
enable = false

[plugins.mongodb]
host = "localhost"
port = "27017"
database = "FILL ME"
collection = "FILL ME"
username = "FILL ME"
password = "FILL ME"
enable = false

[plugins.nvidia]
poll_interval = "1s"
flush_interval = "5s"
enable = false

[plugins.perf]
poll_interval = "1s"
flush_interval = "5s"
hardware_events = [
    "REF_CPU_CYCLES",
    "CACHE_MISSES",
    "BRANCH_MISSES",
]
software_events = []
cache_events = ["LL_READ_MISS"]
enable = true

[plugins.procfs]
enable = true

[plugins.procfs.kernel]
enabled = true
poll_interval = "5s"

[plugins.procfs.memory]
enabled = true
poll_interval = "5s"
metrics = [
    "MemTotal",
    "MemFree",
    "MemAvailable",
    "Cached",
    "SwapCached",
    "Active",
    "Inactive",
    "Mapped",
]

[plugins.procfs.processes]
enabled = true
refresh_interval = "2s"
strategy = "watcher"

[[plugins.procfs.processes.groups]]
exe_regex = ""
poll_interval = "2s"
flush_interval = "4s"

[plugins.procfs.processes.events]
poll_interval = "1s"
flush_interval = "4s"

[plugins.rapl]
poll_interval = "1s"
flush_interval = "5s"
no_perf_events = false
enable = false

[plugins.relay-client]
client_name = "FILL ME"
relay_server = "[::1]:50051"
buffer_max_length = 4096
buffer_timeout = "30s"
enable = false

[plugins.relay-client.retry]
max_times = 8
initial_delay = "500ms"
max_delay = "4s"

[plugins.relay-server]
address = "[::]:50051"
enable = false

[plugins.socket-control]
socket_path = "alumet-control.sock"
enable = true