max_update_interval = "500ms"

[plugins.rapl]
poll_interval = "1s"
flush_interval = "5s"
no_perf_events = false

[plugins.perf]
poll_interval = "1s"
flush_interval = "5s"
hardware_events = ["REF_CPU_CYCLES", "CACHE_MISSES", "BRANCH_MISSES"]
software_events = []
cache_events = ["LL_READ_MISS"]

[plugins.procfs.kernel]
enabled = true
poll_interval = "5s"

[plugins.procfs.memory]
enabled = true
poll_interval = "5s"
metrics = ["MemTotal", "MemFree", "MemAvailable", "Cached", "SwapCached", "Active", "Inactive", "Mapped"]

[plugins.procfs.processes]
enabled = true
refresh_interval = "2s"
strategy = "watcher"

[[plugins.procfs.processes.groups]]
exe_regex = ""
poll_interval = "2s"
flush_interval = "4s"

[plugins.procfs.processes.events]
poll_interval = "1s"
flush_interval = "4s"

[plugins.csv]
output_path = "alumet-output.csv"
force_flush = true
append_unit_to_metric_name = true
use_unit_display_name = true
csv_delimiter = ";"

[plugins.socket-control]
socket_path = "alumet-control.sock"