---
name: Build Docker images pipeline
on:
  workflow_call:
    inputs:
      target-architecture:
        description: 'What is the architecture we want to build for'
        required: true
        type: string
      build-version:
        description: 'What is the version used to build and tag the RPMs'
        required: true
        type: string
      release-version:
        description: 'What is the release version used to build and tag the RPMs'
        required: true
        type: string
jobs:
  packaging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ["fedora:40", "fedora:41"]
        include:
          - image: fedora:40
            dockerfile: "Dockerfile.fedora"
            artifact_dir: "/tmp/images/fedora-40"
            artifact_name: "fedora-40.tar"

          - image: fedora:41
            dockerfile: "Dockerfile.fedora"
            artifact_dir: "/tmp/images/fedora-41"
            artifact_name: "fedora-41.tar"
    steps:
      - name: Prepare docker image output dir
        run: mkdir -p ${{ matrix.artifact_dir }}

      - name: Build ${{ matrix.image }} image using ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/Dockerfile.rpm
          build-args: |
            IMAGE=${{ matrix.image }}
          outputs: type=tar,dest=${{ matrix.artifact_dir }}/${{ matrix.artifact_name }}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Upload alumet RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_dir }}/${{ matrix.artifact_name }}
