---
name: Build Docker images pipeline
on:
  workflow_call:
    inputs:
      target-architecture:
        description: 'What is the architecture we want to build for'
        required: true
        type: string
      build-version:
        description: 'What is the version used to build and tag the RPMs'
        required: true
        type: string
      release-version:
        description: 'What is the release version used to build and tag the RPMs'
        required: true
        type: string
jobs:
  packaging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-image: ["fedora:40", "fedora:41"]
        include:
          - base-image: fedora:40
            dockerfile: "Dockerfile.fedora"
            artifact-name: "alumet-agent-${{ inputs.build-version }}-${{ inputs.release-version }}.fedora-40.${{ inputs.target-architecture }}.tar"

          - image: fedora:41
            dockerfile: "Dockerfile.fedora"
            artifact-name: "alumet-agent-${{ inputs.build-version }}-${{ inputs.release-version }}.fedora-41.${{ inputs.target-architecture }}.tar"
    steps:
      - run: echo "ARTIFACT_NAME ${{ matrix.artifact-name }}"

      - name: Prepare docker image output dir
        run: mkdir -p /tmp/images/

      - name: Build ${{ matrix.base-image }} image using ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/${{ matrix.dockerfile }}
          build-args: |
            BASE_IMAGE=${{ matrix.base-image }}
          outputs: type=tar,dest=/tmp/images/${{ matrix.artifact-name }}
        env:
          DOCKER_BUILD_SUMMARY: false

      - name: Upload alumet RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target-architecture }}/alumet-agent-${{ inputs.build-version }}-${{ inputs.release-version }}.${{ matrix.os }}.${{ inputs.target-architecture }}.tar
          path: /tmp/images/${{ matrix.artifact-name }}
          #path: ./build/docker/${{ inputs.target-architecture }}/alumet-agent-${{ inputs.build-version }}-${{ inputs.release-version }}.${{ matrix.os }}.${{ inputs.target-architecture }}.tar
