---
name: Build Docker images pipeline
on:
  workflow_call:
    inputs:
      target-architecture:
        description: 'What is the architecture we want to build for'
        required: true
        type: string
      build-version:
        description: 'What is the version used to build and tag the RPMs'
        required: true
        type: string
      release-version:
        description: 'What is the release version used to build and tag the RPMs'
        required: true
        type: string
jobs:
  packaging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: ["fedora:40"]
        include:
          - image: fedora:40
            dockerfile: "Dockerfile.rpm"
    steps:
      - name: Build ${{ matrix.image }} image using ${{ matrix.dockerfile }}
        uses: docker/build-push-action@v6
        with:
          push: false
          file: docker/${{ matrix.dockerfile }}
          build-args: |
            IMAGE=${{ matrix.image }}
        env:
          DOCKER_BUILD_SUMMARY: false
      #- uses: actions/checkout@v4
      #  with:
      #    repository: ahuret/packaging
      #    fetch-tags: 'true'
      #    ref: 'ci/create-rpm-package'
      #    path: 'packaging'
      #
      #- name: Download alumet RPM artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    path: theartifacts
