---
name: Main pipeline

on:
  push:

jobs:
  deb:
    uses: ./.github/workflows/build_deb.yaml
    with:
      arch: "amd64"
      name: "alumet-agent"
      version: 0.8
      revision: 1
      urgency: "medium"
